In [28]:
import pandas as pd 
import numpy as np
from sklearn import linear_model
import pickle
import joblib

In [29]:
df = pd.read_csv("homeprices.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  595000
4  4000  760000
5  4100  810000

In [30]:
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  595000
4  4000  760000

In [31]:
model = linear_model.LinearRegression()
model.fit(df[['area']], df.price)

LinearRegression()

In [32]:
model.coef_

array([167.30954677])

In [33]:
model.intercept_

76692.3818707813

In [34]:
model.predict([[5000]])

array([913240.11571842])

In [35]:
# with open('model_pickle', 'wb') as f:
#     pickle.dump(model, f)

filename = 'model_pickle'
pickle.dump(model, open(filename, 'wb'))

In [36]:
# with open('model_pickle', 'rb') as f:
#     mp = pickle.load(f)

loaded_model = pickle.load(open(filename, 'rb'))

In [37]:
# mp.predict(5000)
loaded_model.predict([[5000]])

array([913240.11571842])

In [38]:
filename = 'model_joblib'
joblib.dump(model, filename)

['model_joblib']

In [39]:
loaded_model = joblib.load(filename)

In [40]:
loaded_model.predict([[5000]])

array([913240.11571842])