In [47]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n

In [48]:
df = pd.read_csv("hiring.csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary
0        NaN                    8.0                           9   50000
1        NaN                    8.0                           6   45000
2       five                    6.0                           7   60000
3        two                   10.0                          10   65000
4      seven                    9.0                           6   70000
5      three                    7.0                          10   62000
6        ten                    NaN                           7   72000
7     eleven                    7.0                           8   80000

In [49]:
df.experience = df.experience.fillna('zero')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary
0       zero                    8.0                           9   50000
1       zero                    8.0                           6   45000
2       five                    6.0                           7   60000
3        two                   10.0                          10   65000
4      seven                    9.0                           6   70000
5      three                    7.0                          10   62000
6        ten                    NaN                           7   72000
7     eleven                    7.0                           8   80000

In [50]:
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary
0           0                    8.0                           9   50000
1           0                    8.0                           6   45000
2           5                    6.0                           7   60000
3           2                   10.0                          10   65000
4           7                    9.0                           6   70000
5           3                    7.0                          10   62000
6          10                    NaN                           7   72000
7          11                    7.0                           8   80000

In [38]:
import math
median_test_score = math.floor(df['test_score(out of 10)'].mean())
median_test_score

7

In [39]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(median_test_score)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary
0           0                    8.0                           9   50000
1           0                    8.0                           6   45000
2           5                    6.0                           7   60000
3           2                   10.0                          10   65000
4           7                    9.0                           6   70000
5           3                    7.0                          10   62000
6          10                    7.0                           7   72000
7          11                    7.0                           8   80000

In [40]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']], df.salary)

LinearRegression()

In [41]:
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [42]:
reg.intercept_

14992.651446693118

In [43]:
reg.predict([[2, 9, 6]])

array([53713.86677124])

In [45]:
# y = m1 * x1 + m2 * x2 + m3 * x3 + b

2922.26901502 * 2 + 2221.30909959 * 9 + 2147.48256637 * 6 + 14992.651446693118

53713.86677126312

In [46]:
reg.predict([[12, 10, 10]])

array([93747.79628651])